// Git-Sync Types
//
// A vault can have multiple git remotes, but its working directory can only
// be checked out on one branch at a time — so the branch is a vault-level
// setting shared by all remotes, while each remote has its own URL,
// credentials, and sync interval. See .kiro/specs/git-sync/design.md.

export type GitAuthMethod = 'https-token' | 'ssh-key'
export type GitSyncResult = 'success' | 'error' | 'conflict'

export interface GitSyncRemoteConfig {
  id: string
  vaultId: string
  name: string
  remoteUrl: string
  authMethod: GitAuthMethod
  /**
   * Public half of the configured SSH key, derived server-side via
   * `ssh-keygen -y` from whatever private key is stored (generated by
   * Slatebase or pasted in by hand) so it can be shown for copying into
   * GitHub as a deploy key. `null` for `https-token` remotes. Optional so
   * records persisted before this field existed still parse correctly.
   */
  publicKey?: string | null
  intervalMinutes: number
  enabled: boolean
  createdAt: string
  updatedAt: string
}

/** Everything persisted for one vault's git-sync setup. */
export interface GitSyncVaultData {
  branch: string
  remotes: GitSyncRemoteConfig[]
}

export interface GitSyncRemoteStatus {
  remoteId: string
  lastRunAt: string | null
  lastResult: GitSyncResult | null
  lastError: string | null
  conflictFiles: string[]
  /** Files brought in by the last successful merge. `null` when not applicable (error/conflict/no run yet). */
  lastPulledFiles: number | null
  /** Files committed locally and pushed in the last successful run. `null` when not applicable. */
  lastPushedFiles: number | null
}

/** Per-vault map of remoteId -> status, as persisted on disk. */
export type GitSyncStatusMap = Record<string, GitSyncRemoteStatus>

/** Credential for one sync run, resolved from the secret store just before use — never persisted alongside the config. */
export type GitAuthContext =
  | { method: 'https-token'; token: string }
  | { method: 'ssh-key'; privateKey: string; knownHostsPath: string }
